backend:
  name: git-gateway
  branch: main

media_folder: "img/uploads"
public_folder: "/img/uploads"

collections:
  - name: "about"
    label: "About"
    files:
      - name: "about"
        label: "About Page"
        file: "content/about.md"
        fields:
          - { name: "title", label: "Title", widget: "string" }
          - { name: "body", label: "Body", widget: "markdown" }

  - name: "publications"
    label: "Publications"
    folder: "content/publications"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "authors", label: "Authors", widget: "string" }
      - { name: "journal", label: "Journal", widget: "string" }
      - { name: "year", label: "Year", widget: "number" }
      - { name: "abstract", label: "Abstract", widget: "text" }
      - { name: "link", label: "Link", widget: "string" }

  - name: "teaching"
    label: "Teaching"
    folder: "content/teaching"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "course_name", label: "Course Name", widget: "string" }
      - { name: "description", label: "Description", widget: "text" }

  - name: "projects"
    label: "Projects"
    folder: "content/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Project Title", widget: "string" }
      - { name: "description", label: "Description", widget: "markdown" }
      - { name: "image", label: "Image URL", widget: "string" }
      - { name: "link", label: "Project Link", widget: "string" }

  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "body", label: "Body", widget: "markdown" }
